hello-world:
    path: /
    controller: App\Controller\HelloWorldController::index
    methods: GET

hello-world-test:
    path: /test
    controller: App\Controller\HelloWorldController::test
    methods: GET

registry:
    path: /yarn/-/npm/v1/security/audits
    controller: App\Controller\RegistryTestController::index
    methods: POST

registry-error:
    path: /yarn/error/-/npm/v1/security/audits
    controller: App\Controller\RegistryTestController::error
    methods: POST

