hello-world:
    path: /
    controller: App\Controller\HelloWorldController::index
    methods: GET

index:
    path: /-/npm/v1/security/audits
    controller: App\Controller\ProxyController::index
    methods: POST