home:
    path: /
    controller: App\Infrastructure\Controller\HomeController::index
    methods: GET

index:
    path: /-/npm/v1/security/audits
    controller: App\Infrastructure\Controller\ProxyController::index
    methods: POST